services:
  web:
    build: .
    volumes:
      - ./db:/app/db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DJANGO_DB_PATH=/app/db/db.sqlite3
    restart: on-failure

volumes:
  sqlite_data:
    driver: local  # Explicitly set the local driver 