services:
  web:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID:-1000}  # Pass host user ID to Dockerfile
    volumes:
      - ./db:/app/db
      - static_volume:/app/staticfiles
      - /etc/yourcinemafilms/env.py:/etc/yourcinemafilms/env.py:ro  # Mount only the environment file as read-only
    environment:
      - DJANGO_DB_PATH=/app/db/db.sqlite3
      - HOST_UID=${HOST_UID:-1000}  # Make HOST_UID available in container
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt # Mount Let's Encrypt certificates
      - static_volume:/app/staticfiles # Mount static files at the same path as in the Nginx config
      - /etc/yourcinemafilms/env.py:/etc/yourcinemafilms/env.py:ro  # Mount env.py to read production value
    depends_on:
      - web

volumes:
  static_volume:
    driver: local  # For storing static files
  sqlite_data:
    driver: local  # For storing database files
