services:
  web:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID:-1000}  # Pass host user ID to Dockerfile
    volumes:
      - ./db:/app/db
      - /etc/yourcinemafilms/env.py:/etc/yourcinemafilms/env.py:ro  # Mount only the environment file as read-only
      - static_data:/app/staticfiles  # Use a named volume for static files
    environment:
      - DJANGO_DB_PATH=/app/db/db.sqlite3
      - HOST_UID=${HOST_UID:-1000}  # Make HOST_UID available in container
      - DJANGO_ALLOWED_HOSTS=yourcinemafilms.theworkpc.com,localhost,127.0.0.1
      - PYTHONPATH=/etc/yourcinemafilms:/app  # Add env.py directory to Python path
    security_opt:
      - no-new-privileges:true
    read_only: false  # Changed to false to allow writing to static files
    tmpfs:
      - /tmp:size=256M  # Temporary storage
      - /run
      - /run/nginx:rw  # Add nginx run directory with write permissions
      - /var/lib/nginx:rw  # Add nginx temp directory with write permissions
      - /var/log/nginx:rw  # Add nginx log directory with write permissions
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount Let's Encrypt certificates
      - static_data:/var/www/YourCinemaFilms/staticfiles:ro # Mount static files as read-only
    security_opt:
      - no-new-privileges:true
    read_only: false  # Changed to allow writing to static files
    tmpfs:
      - /tmp:size=64M
      - /run
      - /run/nginx:rw  # Add nginx run directory with write permissions
      - /var/lib/nginx:rw  # Add nginx temp directory with write permissions
      - /var/log/nginx:rw  # Add nginx log directory with write permissions
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_data:
    driver: local  # For storing static files
  sqlite_data:
    driver: local  # For storing database files
