services:
  - type: web
    name: yourcinemafilms
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn films_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: films_project.settings
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yourcinemafilms-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: UPCOMING_FILMS_MONTHS
        value: "6"
      - key: TMDB_SORT_BY
        value: "popularity.desc"

  - type: cron
    name: update-cinema-cache
    env: python
    schedule: "0 0 * * *"  # Run at midnight UTC every day
    buildCommand: pip install -r requirements.txt
    startCommand: python update_cinema_cache.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: films_project.settings
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yourcinemafilms-db
          property: connectionString
      - key: UPCOMING_FILMS_MONTHS
        value: "6"
      - key: TMDB_SORT_BY
        value: "popularity.desc"

  - type: job
    name: apply-migrations
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python apply_migrations.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: films_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: yourcinemafilms-db
          property: connectionString

databases:
  - name: yourcinemafilms-db
    databaseName: yourcinemafilms
    user: yourcinemafilms 