services:
  - type: web
    name: yourcinemafilms
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn films_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: films_project.settings
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yourcinemafilms-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: UPCOMING_FILMS_MONTHS
        value: "6"
      - key: TMDB_SORT_BY
        value: "revenue.desc,vote_count.desc,popularity.desc"
      - key: CACHE_UPDATE_INTERVAL_MINUTES
        value: "1440"  # 24 hours in minutes - prevent duplicate runs

  - type: cron
    name: update-cinema-cache
    env: python
    schedule: "0 2 * * *"  # Run at 2 AM UTC every day (less busy time)
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py update_movie_cache --all-pages --force
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: films_project.settings
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yourcinemafilms-db
          property: connectionString
      - key: UPCOMING_FILMS_MONTHS
        value: "6"
      - key: TMDB_SORT_BY
        value: "revenue.desc,vote_count.desc,popularity.desc"
      - key: CACHE_UPDATE_INTERVAL_MINUTES
        value: "1440"  # 24 hours in minutes - prevent duplicate runs

databases:
  - name: yourcinemafilms-db
    databaseName: yourcinemafilms
    user: yourcinemafilms 