# Generated by Django 5.1.1 on 2025-03-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', 'add_google_account_id'),
        ('films_app', 'add_profile_picture_url'),
    ]

    operations = [
    ]
