# Generated by Django 5.1.1 on 2025-03-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0002_merge_add_google_account_id_add_profile_picture_url'),
        ('films_app', 'add_email_fields'),
    ]

    operations = [
    ]
