# Generated by Django 5.1.1 on 2025-03-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0003_merge_20250307_2026'),
        ('films_app', 'ensure_tables'),
    ]

    operations = [
    ]
