# Generated by Django 5.1.1 on 2025-03-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0005_userprofile_cinema_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='film_genres',
            field=models.TextField(blank=True, help_text='What film genres do you prefer to see in the cinema?', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your city, town or region in the UK', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('profile_complete', 'Profile Completed'), ('first_vote', 'First Vote'), ('ten_votes', '10 Votes'), ('fifty_votes', '50 Votes'), ('first_tag', 'First Genre Tag'), ('tag_approved', 'Genre Tag Approved'), ('cinema_expert', 'Cinema Expert')], max_length=50)),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['achievement_type'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
