# Generated by Django 5.1.1 on 2025-03-09 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0009_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_in_cinema',
            field=models.BooleanField(default=False, help_text='Whether this film is currently in UK cinemas'),
        ),
        migrations.AddField(
            model_name='film',
            name='uk_certification',
            field=models.CharField(blank=True, help_text='UK certification (e.g., PG, 12A, 15)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='uk_release_date',
            field=models.DateField(blank=True, help_text='UK release date for this film', null=True),
        ),
        migrations.CreateModel(
            name='CinemaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_votes', to='films_app.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'film')},
            },
        ),
    ]
