# Generated by Django 5.1.1 on 2025-03-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0011_film_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='popularity',
        ),
    ]
