# Generated by Django 5.1.1 on 2025-03-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0012_remove_film_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='popularity',
            field=models.FloatField(default=0, help_text='Popularity score from TMDB API'),
        ),
    ]
