# Generated by Django 5.1.1 on 2025-03-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0011_film_popularity'),
        ('films_app', '0012_add_film_popularity'),
    ]

    operations = [
    ]
