# Generated by Django 5.1.1 on 2025-03-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0013_merge_0011_film_popularity_0012_add_film_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(choices=[('now_playing', 'Now Playing'), ('upcoming', 'Upcoming')], max_length=20, unique=True)),
                ('last_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
