# Generated by Django 5.1.1 on 2025-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0015_remove_userprofile_favorite_cinema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='needs_status_check',
            field=models.BooleanField(default=False, help_text='Flag indicating this film needs a priority status check'),
        ),
    ]
