# Generated by Django 5.1.1 on 2025-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0016_add_status_check_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(default=0, help_text='Average vote score from TMDB API (0-10)'),
        ),
        migrations.AddField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(default=0, help_text='Number of votes from TMDB API'),
        ),
    ]
