# Generated by Django 5.1.1 on 2025-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0017_film_vote_average_film_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='revenue',
            field=models.BigIntegerField(default=0, help_text='Total box office revenue in USD from TMDB API'),
        ),
    ]
