# Generated by Django 5.1.1 on 2025-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0018_film_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Whether this film is scheduled for future UK release'),
        ),
    ]
