# Generated by Django 5.1.1 on 2025-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0019_film_is_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='films_per_page',
            field=models.PositiveIntegerField(choices=[(4, '4 films per page'), (8, '8 films per page'), (12, '12 films per page'), (16, '16 films per page'), (20, '20 films per page')], default=8, help_text='Number of films to display per page'),
        ),
    ]
