# Generated by Django 5.1.1 on 2025-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0020_userprofile_films_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cinema',
            field=models.CharField(blank=True, help_text='Your preferred cinema or chain', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cinema_privacy',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('users', 'Users - Visible to registered users only'), ('private', 'Private - Visible to only me')], default='private', max_length=10),
        ),
    ]
